FROM maven:3.6.1-jdk-8-slim AS build
RUN mkdir -p /workspace
WORKDIR /workspace
COPY pom.xml /workspace
COPY src /workspace/src
RUN mvn -f pom.xml clean package

### STAGE 1: Build ###
#FROM node:12.7-alpine AS buildui
#WORKDIR /usr/src/app
#COPY /mc-ui/package.json  /usr/src/app/
#RUN npm install
#COPY ./mc-ui/ /usr/src/app
## naresh #RUN npm run build
#RUN npm run build:prod

#FROM tomcat:latest
FROM tomcat:jdk8-openjdk
#FROM tomcat:9.0.39-jdk8-openjdk-buster
# change for memory
# for file share
RUN mkdir -p  /User/File/TimeSheet/files/

ENV CATALINA_OPTS="-Xms1G -Xmx1G"
COPY --from=build /workspace/target/*.war /usr/local/tomcat/webapps/mtimesheet.war
#COPY --from=buildui  usr/src/app/dist   /usr/local/tomcat/webapps/mc-ui
#COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml
#COPY context.xml /usr/local/tomcat/conf/context.xml


EXPOSE 8080
CMD ["catalina.sh", "run"]

#FROM openjdk:8-alpine
#COPY --from=build /workspace/target/*.jar app.jar
#EXPOSE 8080
#ENTRYPOINT ["java","-jar","app.jar"]
