version: '3.1'
services:
  mysqldb:
    # Currently the latest version is MySQL8.x
    image: mysql
    container_name: mysqldb8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Timesheet@123
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - 3307:3306
#    volumes:
#      - mc-scrum-data:/var/lib/postgresql/datamc
    networks:
      - scrum-network

    volumes:
      - /awss3datapp/data:/var/lib/mysql
        #     - /awss3data/data:/var/lib/mysql
      ### naresh 9/13- ./data:/var/lib/mysql
  # MySQL web client
  adminer:
    image: adminer
    restart: always
    ports:
      - 8099:8080
    networks:
      - scrum-network
  ts-app-pp:
    #The docker file in scrum-app build the jar and provides the docker image with the following name.
    build: ./
    container_name: ts-app-pp-c

    ports:
      - 8084:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    networks:
      - scrum-network
    volumes:
      - /awss3datapp/Filedata:/User/File/TimeSheet/files/
    links:
      - mysqldb

  ts-app-sb24:
    #The docker file in scrum-app build the jar and provides the docker image with the following name.
    build: ./timesheet_sb24
    container_name: ts-app-sb24-c

    #Environment variables for Spring Boot Application.
   # environment:
   #   - DB_SERVER=mc-postgres-12
   #   - POSTGRES_APP_DB=mc_master
   #   - POSTGRES_DB=mc_master
   #   - POSTGRES_USER=postgres
   #   - POSTGRES_PASSWORD=postgres
    ports:
      - 8083:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
        #    networks:
        #- scrum-network
    networks:
      - scrum-network
    volumes:
      - /awss3datasb24/Filedata:/User/File/TimeSheet/files/
#      - ./tomcat-1/conf:/usr/local/tomcat/conf
#      - ./tomcat-1/logs:/usr/local/tomcat/logs
#      - ./tomcat-1/webapps:/usr/local/tomcat/webapps
#
    links:
      - mysqldb
        #nginxlb:
    #The docker file in scrum-app build the jar and provides the docker image with the following name.
  nginx:
    image: nginx:latest
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ts-app-sb24
      - ts-app-pp  
    ports:
            #      - 80:80
      - 8080:80
    networks:
      - scrum-network

networks:
  scrum-network:
    driver: bridge
    # name: ts-app
