package com.aim.enums;

public enum ActivityType {
	DELETE_TIMESHEET, 
	REJECT_TIMESHEET, 
	APPROVE_TIMESHEET, 
	DOWNLOAD_FILE, 
	RESUBMIT_TIMESHEET, 
	SUBMIT_TIMESHEET,
	ADD_USER,
	EDIT_USER,
	DELETE_USER,
	ACTIVE_USER,
	DEACTIVE_USER,
	SET_USER_DETAILS,
	SCHEDULAR_MAIL_SEND
	
}
